---
name: Slapper
version: 1.0.0
main: org.mdafftfa.Slapper
author: mdafftfa
api: 2.0.0

permissions:
  rca.command:
    default: op
    description: Allow using command /rca

  slapper.command.cancel:
    default: op
    description: Allow using command /slapper cancel
  slapper.command.spawn:
    default: op
    description: Allow using command /slapper spawn
  slapper.command.edit:
    default: op
    description: Allow using command /slapper edit
  slapper.command.remove:
    default: op
    description: Allow using command /slapper remove
  slapper.command.id:
    default: op
    description: Allow using command /slapper id
  slapper.command.list:
    default: op
    description: Allow using command /slapper list
  slapper.command.help:
    default: op
    description: Allow using command /slapper help
...